#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [--help]

Generate one Markdown debug report on stdout.

The report is read-only and includes:
  - system diagnostic
  - Bluetooth state
  - BlueZ D-Bus objects
  - bluetooth.service status and logs
  - rfkill state
  - PipeWire/WirePlumber/oFono summaries
  - local network summary
  - recommendations
EOF
}

have_command() {
  command -v "$1" >/dev/null 2>&1
}

system_bus_available() {
  have_command busctl && busctl --system list >/dev/null 2>&1
}

user_bus_available() {
  have_command busctl && busctl --user list >/dev/null 2>&1
}

heading() {
  printf '\n## %s\n\n' "$1"
}

run_block() {
  local title="$1"
  shift
  heading "$title"
  printf '```text\n'
  "$@" 2>&1 || printf 'WARNING command failed: %s\n' "$*"
  printf '```\n'
}

print_unavailable() {
  printf '```text\nWARNING %s\n```\n' "$1"
}

recommendations() {
  heading "Recommendations"
  cat <<'EOF'
- Run `./server/install.sh --check` to review missing packages.
- Run `./server/check-system.sh` after installing dependencies on the Raspberry Pi.
- Run `./server/configure-bluetooth.sh --apply` to start BlueZ and prepare a temporary pairing window.
- Run `./server/pair-phone.sh --discoverable`, then pair from Android Bluetooth settings.
- Verify Android shows PhoneBridge as connected for calls.
- If Android pairs but does not show call support, capture this report and inspect HFP backend support before changing configuration.
EOF
}

main() {
  case "${1:-}" in
    -h | --help)
      usage
      return 0
      ;;
    "")
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      return 2
      ;;
  esac

  printf '# PhoneBridge Bluetooth Debug Report\n\n'
  printf -- '- Generated by: `%s`\n' "$SCRIPT_NAME"
  printf -- '- Generated at: `%s`\n' "$(date -Is)"
  printf -- '- Mode: read-only\n'

  run_block "PhoneBridge System Check" "$ROOT_DIR/server/check-system.sh"

  run_block "bluetooth.service Status" systemctl status bluetooth.service --no-pager
  run_block "bluetooth.service Journal" journalctl -u bluetooth.service -n 120 --no-pager -q

  if have_command rfkill; then
    run_block "rfkill" rfkill list
  else
    heading "rfkill"
    print_unavailable "rfkill is unavailable"
  fi

  if have_command bluetoothctl && system_bus_available; then
    run_block "bluetoothctl show" bluetoothctl show
    run_block "bluetoothctl devices" bluetoothctl devices
    run_block "bluetoothctl paired-devices" bluetoothctl paired-devices
  else
    heading "bluetoothctl"
    print_unavailable "bluetoothctl or system D-Bus is unavailable"
  fi

  if system_bus_available; then
    run_block "D-Bus org.bluez Tree" busctl --system tree org.bluez
    run_block "D-Bus org.bluez Service Introspection" busctl --system introspect org.bluez /org/bluez
    run_block "D-Bus org.ofono Tree" busctl --system tree org.ofono
  else
    heading "D-Bus"
    print_unavailable "system D-Bus is unavailable"
  fi

  run_block "ofono.service Status" systemctl status ofono.service --no-pager

  if have_command wpctl && user_bus_available; then
    run_block "wpctl status" wpctl status
  else
    heading "wpctl status"
    print_unavailable "wpctl or user D-Bus is unavailable"
  fi

  if have_command pw-cli && user_bus_available; then
    run_block "PipeWire Nodes" pw-cli ls Node
  else
    heading "PipeWire Nodes"
    print_unavailable "pw-cli or user D-Bus is unavailable"
  fi

  if have_command ip; then
    run_block "Local Network Addresses" ip -brief addr
    run_block "Local Routes" ip route
  else
    heading "Network"
    print_unavailable "ip command is unavailable"
  fi

  recommendations
}

main "$@"
