#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [--help]

Collect a read-only PhoneBridge debug snapshot:
  - server/check-system.sh
  - service states
  - Bluetooth state
  - PipeWire/WirePlumber state
  - oFono state
  - local network summary
EOF
}

have_command() {
  command -v "$1" >/dev/null 2>&1
}

system_bus_available() {
  have_command busctl && busctl --system list >/dev/null 2>&1
}

user_bus_available() {
  have_command busctl && busctl --user list >/dev/null 2>&1
}

section() {
  printf '\n== %s ==\n' "$1"
}

run_section() {
  local title="$1"
  shift
  section "$title"
  "$@" 2>&1 || printf 'WARNING command failed: %s\n' "$*"
}

recommendations() {
  section "Recommendations"
  printf 'INFO run ./server/install.sh --check to review missing packages\n'
  printf 'INFO run ./server/check-system.sh after installing dependencies on the Raspberry Pi\n'
  printf 'INFO use ./server/configure-bluetooth.sh --check before any pairing attempt\n'
  printf 'INFO do not force HFP/HSP roles until Android pairing behavior is captured on real hardware\n'
  printf 'INFO document uncertain behavior in docs/research/decision-log.md before implementation\n'
}

service_state() {
  local service_name="$1"
  if have_command systemctl; then
    systemctl status "$service_name" --no-pager 2>/dev/null || printf 'WARNING %s is unavailable or inactive\n' "$service_name"
  else
    printf 'WARNING systemctl is unavailable\n'
  fi
}

user_service_state() {
  local service_name="$1"
  if have_command systemctl; then
    systemctl --user status "$service_name" --no-pager 2>/dev/null || printf 'WARNING user %s is unavailable or inactive\n' "$service_name"
  else
    printf 'WARNING systemctl is unavailable\n'
  fi
}

main() {
  case "${1:-}" in
    -h | --help)
      usage
      return 0
      ;;
    "")
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      return 2
      ;;
  esac

  section "PhoneBridge debug snapshot"
  printf 'Generated by %s\n' "$SCRIPT_NAME"
  printf 'This script is read-only.\n'

  run_section "PhoneBridge system check" "$ROOT_DIR/server/check-system.sh"

  section "Service states"
  service_state bluetooth.service
  service_state ofono.service
  user_service_state pipewire.service
  user_service_state pipewire-pulse.service
  user_service_state wireplumber.service

  if have_command bluetoothctl && system_bus_available; then
    run_section "Bluetooth controllers" bluetoothctl list
    run_section "Bluetooth default controller" bluetoothctl show
    run_section "Bluetooth paired devices" bluetoothctl devices Paired
  else
    section "Bluetooth controllers"
    printf 'WARNING bluetoothctl or system D-Bus is unavailable\n'
  fi

  if have_command rfkill; then
    run_section "rfkill" rfkill list
  fi

  if have_command wpctl && user_bus_available; then
    run_section "wpctl status" wpctl status
  else
    section "wpctl status"
    printf 'WARNING wpctl or user D-Bus is unavailable\n'
  fi

  if have_command pw-cli && user_bus_available; then
    run_section "PipeWire nodes" pw-cli ls Node
  else
    section "PipeWire nodes"
    printf 'WARNING pw-cli or user D-Bus is unavailable\n'
  fi

  if system_bus_available; then
    run_section "oFono D-Bus tree" busctl --system tree org.ofono
  else
    section "oFono D-Bus tree"
    printf 'WARNING system D-Bus is unavailable\n'
  fi

  if have_command ip; then
    run_section "local network addresses" ip -brief addr
    run_section "local routes" ip route
  fi

  recommendations
}

main "$@"
